name: itcast

person:
      name: 张三
      age: 22
      addr: 北京


person1: {name: 李四,age: 24,addr: 上海}


server:
    port: 8091
    servlet:
      context-path: /demo

city:
  - beijing
  - shanghai
  - shenzhen

city1: [beijing,shanghai,shenzhen]